import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className='min-h-screen py-16 flex-1 flex flex-col justify-center items-center text-9xl'>
          Welcome to <Link className='text-blue-500 border-b-8 border-blue-500 hover:font-bold' href="./posts/Converter">Radix Converter</Link>
        </h1>
      </main>
    </div>
  )
}
